# GitHub 构建 Java 应用

name: build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
#  build-ubuntu:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - run: make vbox.init
  build-macos:
    runs-on: macos-latest
#    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - run: make vbox.init

