# GitHub 构建 Java 应用

name: build

on:
  push:
    branches: [ vdi ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
#  build-ubuntu:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - run: make vbox.init
  build-macos:
    runs-on: macos-latest
#    runs-on: macos-13
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v3
        with:
          # 默认不会检出大文件
          lfs: true
      - run: make vbox.lifecycle.test guest.lifecycle.test

